### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by davisdude** [jakedeichert/mandarin-syntax#2]
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

Also in index.less:

Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by jakedeichert** [comment]
I'm assuming this must be the new standard way? I haven't looked at other syntax packages in a while...

Tomorrow I'll probably get a chance to make those changes and I'll take a look at other recently updated packages to see if there's anything else I need to change to catch up.

**Comment by davisdude** [comment]
Yeah, there's a warning sign that pops up in the lower-right corner that gives those two warnings.

**Comment by jakedeichert** [comment]
Fixed in commit 91b8acb

**Comment by davisdude** [comment]
Thanks
